services:
  airflow-webserver:
    image: apache/airflow:2.6.1
    restart: always
    depends_on:
      - airflow-scheduler
      - airflow-postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      - AIRFLOW__WEBSERVER__WEB_SERVER_HOST=0.0.0.0
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/usr/local/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/logs:/usr/local/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/config:/usr/local/airflow/config
      - ${AIRFLOW_PROJ_DIR:-.}/plugins:/usr/local/airflow/plugins

    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.6.1
    restart: always
    depends_on:
      - airflow-postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/usr/local/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/logs:/usr/local/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/config:/usr/local/airflow/config
      - ${AIRFLOW_PROJ_DIR:-.}/plugins:/usr/local/airflow/plugins
    command: scheduler

  airflow-postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
